catalog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import re_path
from django.views.generic import RedirectView

from catalog import views


urlpatterns = [
    re_path(r"^$", views.index, name="index"),
    re_path(r"^about/$", views.about, name="about"),
    re_path(r"^by-(?P<report_tag>[a-z0-9-]+)/$", views.report, name="report"),
    re_path(
        r"^by-(?P<report_tag>[a-z0-9-]+)/(?P<entry_tag>[a-z0-9-]+)/$",
        views.report_details,
        name="report_details",
    ),
    re_path(r"^(?P<category_tag>[a-z0-9-]+)/$", views.category, name="category"),
    re_path(
        r"^(?P<category_tag>[a-z0-9-]+)/(?P<item_tag>[a-z0-9-]+)/$",
        views.item,
        name="item",
    ),
    re_path(r"^default\.asp$", RedirectView.as_view(pattern_name="index")),
    re_path(r"^item\.asp$", views.legacy_item, name="legacy_item"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = views.handle404

merch/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import re_path

from merch import views


urlpatterns = [
    re_path(r"^$", views.index, name="index"),
    re_path(r"^search/$", views.search, name="search"),
    re_path(r"^peelitback2025poster/$", views.posters, name="posters"),
    re_path(r"^poster-gallery/(?P<poster_id>\d+)/$", views.poster_gallery, name="poster_gallery"),
    re_path(r"^(?P<category_tag>[a-z0-9-]+)/$", views.category, name="category"),
    re_path(
        r"^(?P<category_tag>[a-z0-9-]+)/(?P<product_tag>[a-z0-9-]+)/$",
        views.product,
        name="product",
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

nincatalog/urls.py
from django.conf import settings
from django.urls import re_path
from django.conf.urls.static import static
from django.contrib import admin

from catalog.views import handle404


urlpatterns = [re_path(r"^", admin.site.urls)] + static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)

handler404 = handle404

catalog/models.py
from django.db import models
from django.utils.text import slugify
from model_clone import CloneMixin


class Artist(models.Model):
    name = models.CharField(max_length=200)

    class Meta:
        ordering = ("name",)

    def __str__(self):
        return self.name


class Category(models.Model):
    name = models.CharField(max_length=200)
    tag = models.CharField(max_length=200)
    halo = models.PositiveSmallIntegerField(blank=True, null=True)
    icon = models.ImageField(upload_to="categories")

    class Meta:
        verbose_name_plural = "Categories"

    def __str__(self):
        label = self.name
        if self.halo is not None:
            label = "%s (Halo %d)" % (label, self.halo)
        return label


class MediaPackage(models.Model):
    name = models.CharField(max_length=200)

    class Meta:
        ordering = ("name",)
        verbose_name_plural = "Media Packages"

    def __str__(self):
        return self.name


class MediaFormat(models.Model):
    name = models.CharField(max_length=200)
    tag = models.CharField(max_length=200, default="")

    class Meta:
        ordering = ("name",)
        verbose_name_plural = "Media Formats"

    def __str__(self):
        return self.name


class Country(models.Model):
    name = models.CharField(max_length=200)
    code = models.CharField(max_length=2)
    icon = models.ImageField(upload_to="countries")

    class Meta:
        ordering = ("name",)
        verbose_name_plural = "Countries"

    def __str__(self):
        return self.name


class MusicLabel(models.Model):
    name = models.CharField(max_length=200)
    url = models.URLField()
    icon = models.ImageField(upload_to="music_labels", null=True)

    class Meta:
        ordering = ("name",)
        verbose_name_plural = "Music Labels"

    def __str__(self):
        return self.name


class Era(models.Model):
    name = models.CharField(max_length=200)
    description = models.CharField(max_length=200)
    icon = models.ImageField(upload_to="eras")

    def __str__(self):
        return self.name


class ItemRarity(models.Model):
    code = models.CharField(max_length=1)
    description = models.CharField(max_length=200)
    icon = models.ImageField(upload_to="rarity")
    scale_icon = models.ImageField(upload_to="rarity")

    class Meta:
        ordering = ("id",)
        verbose_name_plural = "Item Rarities"

    def __str__(self):
        return self.code


class Item(CloneMixin, models.Model):
    name = models.CharField(max_length=200)
    description = models.CharField(max_length=200)
    artist = models.ForeignKey(Artist, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    media_format = models.ForeignKey(MediaFormat, on_delete=models.CASCADE)
    media_package = models.ForeignKey(MediaPackage, on_delete=models.CASCADE)
    media_notes = models.CharField(max_length=200)
    country = models.ForeignKey(Country, on_delete=models.CASCADE)
    music_labels = models.ManyToManyField(MusicLabel)
    year = models.IntegerField()
    rarity = models.ForeignKey(ItemRarity, on_delete=models.CASCADE)
    rarity_date = models.DateField(null=True, blank=True)
    era = models.ForeignKey(Era, null=True, on_delete=models.CASCADE)
    notes = models.TextField()
    catalog_number = models.CharField(max_length=200)
    upc = models.CharField(max_length=200)
    discogs = models.IntegerField(null=True, blank=True)
    is_promo = models.BooleanField(default=False)
    is_authorized = models.BooleanField(default=False)
    release_date = models.DateField(null=True, blank=True)
    added_date = models.DateField(null=True, blank=True)
    old_key = models.CharField(max_length=8, null=True, blank=True)

    _clone_excluded_fields = ["old_key"]
    _clone_m2m_fields = ["music_labels"]

    class Meta:
        ordering = (
            "year",
            "release_date",
            "name",
            "media_format",
            "country",
            "catalog_number",
        )

    def __str__(self):
        return "%s (%s %s)" % (self.name, self.country.code, self.media_format.name)

    def tag(self):
        return slugify(
            "-".join(
                [self.name, self.country.code, self.media_format.tag, str(self.id)]
            )
        )


class ItemImageType(models.Model):
    name = models.CharField(max_length=200)

    class Meta:
        ordering = ("name",)
        verbose_name_plural = "Item Image Types"

    def __str__(self):
        return self.name


class ItemImage(models.Model):
    image = models.ImageField(upload_to="item_images")
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    type = models.ForeignKey(ItemImageType, on_delete=models.CASCADE)
    order = models.PositiveSmallIntegerField(default=0)

    class Meta:
        ordering = ("order",)
        verbose_name_plural = "Item Images"

    def __str__(self):
        return "%s [%s]" % (self.item, self.type)


class Report(models.Model):
    name = models.CharField(max_length=200)
    tag = models.CharField(max_length=200)
    model = models.CharField(max_length=200)
    field = models.CharField(max_length=200)
    icon = models.ImageField(upload_to="reports")
    n_columns = models.PositiveSmallIntegerField(default=3)
    column_width = models.PositiveSmallIntegerField(blank=True, null=True)

    def __str__(self):
        return self.name


class Track(models.Model):
    order = models.IntegerField()
    number = models.CharField(max_length=5)
    name = models.CharField(max_length=200)
    length = models.DurationField()
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    artist = models.CharField(max_length=200)
    old_key = models.CharField(max_length=11, null=True, blank=True)

    class Meta:
        ordering = ("order",)

    def __str__(self):
        return self.name

catalog/views.py
from django.http import Http404, HttpResponsePermanentRedirect
from django.shortcuts import render, get_object_or_404
from django.db.models import Count, F
from django.urls import reverse

from catalog.models import (
    Artist,
    Category,
    Country,
    Era,
    Item,
    ItemRarity,
    MediaFormat,
    MediaPackage,
    MusicLabel,
    Report,
)


def index(request):
    _halo_group = Category.objects.filter(halo__isnull=False).order_by("halo")
    _other_group = (
        Category.objects.filter(halo__isnull=True)
        .annotate(n_item=Count("item"))
        .filter(n_item__gt=0)
    )
    _report_group = Report.objects.all()
    return render(
        request,
        "catalog/index.html",
        {
            "halo_group": _halo_group,
            "other_group": _other_group,
            "report_group": _report_group,
        },
    )


def category(request, category_tag):
    _category = get_object_or_404(Category, tag=category_tag)
    _group = header_group(_category.halo is not None)
    _items = _category.item_set.all()
    if "sort" in request.GET:
        sort_field = {
            "artist": "artist__name",
            "title": "name",
            "notes": "description",
            "format": "media_format__name",
            "catalog": "catalog_number",
            "year": "year",
            "country": "country__name",
            "rarity": "rarity__id",
        }.get(request.GET["sort"], "name")
        _items = _items.order_by(sort_field)

    _listing = {
        "title": _category.name.lower(),
        "selected": _category,
        "categories": [
            {
                "name": _category.name,
                "halo": _category.halo,
                "tag": _category.tag,
                "items": _items,
            }
        ],
    }
    return render(
        request, "catalog/listing.html", {"listing": _listing, "group": _group}
    )


def item(request, category_tag, item_tag):
    _category = get_object_or_404(Category, tag=category_tag)
    pk = item_tag.split("-")[-1]
    _item = get_object_or_404(Item, pk=pk)
    if _category != _item.category:
        raise Http404

    _group = header_group(_category.halo is not None)
    return render(
        request,
        "catalog/item.html",
        {"category": _category, "group": _group, "item": _item},
    )


def report(request, report_tag):
    _report = get_object_or_404(Report, tag=report_tag)
    model = globals().get(_report.model, None)
    if model is None:
        raise Http404

    _entries = model.objects.annotate(n_items=Count("item")).filter(n_items__gt=0)
    if model is ItemRarity:  # hack for ItemRarity
        _entries = _entries.annotate(name=F("code"))

    col_length = len(_entries) // _report.n_columns
    if len(_entries) % _report.n_columns != 0:
        col_length += 1
    _entries = [_entries[i::col_length] for i in range(col_length)]
    _group = header_group(False)
    return render(
        request,
        "catalog/report.html",
        {"report": _report, "entries": _entries, "group": _group},
    )


def report_details(request, report_tag, entry_tag):
    _report = get_object_or_404(Report, tag=report_tag)
    _model = globals().get(_report.model, None)
    if _model is None:
        raise Http404
    _entry = get_object_or_404(_model, pk=entry_tag)
    _categories = list()
    for _category in Category.objects.all():
        field = _report.field
        if field == "code":  # hack for ItemRarity
            field = "rarity"
            name = _entry.code
        else:
            name = _entry.name

        filter_kwargs = {"category": _category.pk, field: _entry.pk}
        _items = Item.objects.filter(**filter_kwargs)
        if _items.count() > 0:
            _categories.append(
                {
                    "name": "%s / %s" % (name, _category.name),
                    "halo": _category.halo,
                    "tag": _category.tag,
                    "items": _items,
                }
            )
    _listing = {
        "title": "%s - %s" % (_report.name.lower(), name.lower()),
        "selected": _report,
        "categories": _categories,
    }
    _group = header_group(False)
    return render(
        request, "catalog/listing.html", {"listing": _listing, "group": _group}
    )


def about(request):
    return render(request, "catalog/about.html", {})


def header_group(is_halo):
    if is_halo:
        group = {
            "categories": Category.objects.filter(halo__isnull=False).order_by("halo")
        }
    else:
        categories = (
            Category.objects.filter(halo__isnull=True)
            .annotate(n_item=Count("item"))
            .filter(n_item__gt=0)
        )
        reports = Report.objects.all()
        group = {"categories": categories, "reports": reports}
    return group


def handle404(request, exception):
    response = render(request, "catalog/404.html", {})
    response.status_code = 404
    return response


def legacy_item(request):
    if "key" not in request.GET:
        raise Http404

    _key = request.GET["key"]
    _item = get_object_or_404(Item, old_key=_key)
    _category = _item.category
    return HttpResponsePermanentRedirect(
        reverse("item", kwargs={"category_tag": _category.tag, "item_tag": _item.tag()})
    )

catalog/templates/catalog/about.html
{% extends 'catalog/base.html' %}

{% block content %}
  <div id="about-message">
    <p>welcome.</p>
    <p>this is a project run by active collectors. it is run by fans.</p>
    <p>there are no watermarks. this is not our artwork, nor do we pretend to own rights to any of the items or information documented here.</p>
    <p>additional views are being developed.</p>
    <p>contributors from multiple nations continue to help grow this site.</p>
    <p>please help us expand.</p>
    <p><a href="mailto:contact@nincatalog.com">contact@nincatalog.com</a></p>
  </div>

  <div id="about-status">
    <p>this is nincatalog.com <a title="2015-01-18" href="http://twitter.com/nincatalog">version 3.0a</a>.</p>
  </div>

  {% include 'catalog/footer.html' %}
{% endblock %}

catalog/templates/catalog/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="nincatalog.com">
    <meta name="author" content="nincatalog.com">

    <title>{% block title %}nincatalog.com{% endblock %}</title>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">

    <!-- Optional theme -->
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap-theme.min.css">

    <link rel="stylesheet" href="{% static 'catalog/catalog.css' %}">

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-58668831-1', 'auto');
      ga('send', 'pageview');
    </script>

    <div id="content" class="container">
    {% spaceless %}{% block content %}{% endblock %}{% endspaceless %}
    </div> <!-- /container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
  </body>
</html>

catalog/templates/catalog/category.html
{% extends 'catalog/base.html' %}
{% load staticfiles %}

{% block title %}nincatalog.com :: {{ category.name }}{% endblock %}

{% block content %}
  {% include "catalog/header.html" with group=group selected=category %}
  <div class="row">
    <div id="category-listing" class="col-xs-12">
      <h6>{% if category.halo %}Official Full Releases / {% endif %}{{ category.name }}</h6>
      <table>
        <thead>
          <tr>
            {% if not category.halo %}<th>artist</th>{% endif %}
            <th>title</th>
            <th>notes</th>
            <th class="format">format</th>
            <th>cat number</th>
            <th class="year">yr</th>
            <th class="icon">ctr</th>
            <th class="icon">sc</th>
          </tr>
        </thead>
        <tbody>
        {% for item in category.item_set.all %}
        {% url 'item' category.tag item.pk as item_url %}
          <tr>
            {% if not category.halo %}<td><a href="{{ item_url }}">{{ item.artist.name|lower }}</a></td>{% endif %}
            <td><a href="{{ item_url }}">{{ item.name|lower }}</a></td>
            <td><a href="{{ item_url }}">{{ item.description }}</a></td>
            <td><a href="{{ item_url }}">{{ item.media_format.name }}</a></td>
            <td><a href="{{ item_url }}">{{ item.catalog_number }}</a></td>
            <td class="year"><a href="{{ item_url }}">{{ item.year }}</a></td>
            <td class="icon"><a href="{{ item_url }}"><img src="{{ item.country.icon.url }}" alt="{{ item.country.name }}"/></a></td>
            <td class="icon"><a href="{{ item_url }}"><img src="{{ item.rarity.icon.url }}" alt="{{ item.rarity.code }}" /></a></td>
          </tr>
        {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
  {% include 'catalog/footer.html' %}
{% endblock %}

catalog/templates/catalog/footer.html
{% load static %}
<div id="footer" class="row">
  <div class="col-xs-12">
    <a href="{% url 'index' %}"><img src="{% static 'catalog/img/bottom.jpg' %}"></a>
  </div>
</div>

catalog/templates/catalog/header.html
{% load static %}
<div id="header" class="row">
  <div class="col-xs-12">
    {% for category in group.categories %}
    <a href="{% url 'category' category.tag %}" title="{{ category.name }}">
      <img class="link{% if category == selected %} selected{% endif %}" src="{{ category.icon.url }}" alt="{{ category.name }}"/>
    </a>
    {% endfor %}
    {% for report in group.reports %}
    <a href="{% url 'report' report.tag %}" title="{{ report.name }}">
      <img class="link{% if report == selected %} selected{% endif %}" src="{{ report.icon.url }}" alt="{{ report.name }}"/>
    </a>
    {% endfor %}
    <a href="{% url 'index' %}"><img src="{% static 'catalog/img/itemtop38.jpg' %}"></a>
  </div>
</div>

catalog/templates/catalog/index.html
{% extends 'catalog/base.html' %}
{% load static %}

{% block content %}
    <div class="categories">
    {% for category in halo_group %}
      <a href="{% url 'category' category.tag %}" title="{{ category.name }}">
        <img src="{{ category.icon.url }}" alt="{{ category.name }}"/>
      </a>
    {% endfor %}
    </div>
    <div class="categories reports">
    {% for report in report_group %}
      <a href="{% url 'report' report.tag %}" title="{{ report.name }}">
        <img src="{{ report.icon.url }}" alt="{{ report.name }}"/>
      </a>
    {% endfor %}
    <br>
    {% for category in other_group %}
      <a href="{% url 'category' category.tag %}" title="{{ category.name }}">
        <img src="{{ category.icon.url }}" alt="{{ category.name }}"/>
      </a>
    {% endfor %}
    <a href="{{ request.scheme }}://merch.{{ request.get_host }}" title="Merch">
      <img src="{% static 'catalog/img/merch.png' %}" alt="Merch">
    </a>
    <a href="{% url 'about' %}" title="About the Site">
      <img src="{% static 'catalog/img/about.jpg' %}" alt="About the Site">
    </a>
    </div>
{% endblock %}

catalog/templates/catalog/item.html
{% extends 'catalog/base.html' %}
{% load markdown %}
{% load upc_url %}
{% load track_length %}
{% load track_title %}

{% block title %}nincatalog.com - {{ item }}{% endblock %}

{% block content %}
  {% include 'catalog/header.html' with group=group selected=category %}
  <div id="item-content">
    <div id="item-images">
    {% for image in item.itemimage_set.all %}
        <img src="{{ image.image.url }}" alt="{{ image.type.name }}"/>
    {% endfor %}
    </div>
    <table id="item-core-info">
      <tr><th>band</th><td>{{ item.artist.name|lower }}</td></tr>
      <tr><th>title</th><td>{{ item.name|lower }}</td></tr>
      <tr><th>package</th><td>{{ item.media_notes }}</td></tr>
    </table>
    {% if item.track_set.count %}
    <table id="item-track-listing">
      <tr><th colspan="3">track listing</th></tr>
      {% for track in item.track_set.all %}
      <tr>
        <th></th>
        <td class="track-number">{{ track.number }}.</td>
        <td class="track-name">{{ track|track_title:item.artist.name }}</td>
        <td class="track-length">{{ track.length|track_length }}</td>
      </tr>
      {% endfor %}
    </table>
    {% endif %}
    <table id="item-other-info">
      <tr><th>catalog number</th><td>{{ item.catalog_number }}</td></tr>
      {% if item.upc %}
      <tr><th>upc</th><td><a href="{{ item.upc|upc_url }}" target="_blank">{{ item.upc }}</a></td></tr>
      {% endif %}
      <tr><th>label</th>
        <td>
        {% for label in item.music_labels.all %}
          <a href="{{ label.url }}" title="{{ label.name }}" target="_blank">{{ label.name }}</a>
          {% if not forloop.last %} / {% endif %}
        {% endfor %}
         {{ item.year }}</td>
      </tr>
      <tr><th>country</th><td>{{ item.country.name }} <img src="{{ item.country.icon.url }}" alt="{{ item.country.name }}" /></td></tr>
      {% if item.release_date %}
      <tr><th>release date</th><td>{{ item.release_date|date }}</td></tr>
      {% endif %}
      {% if item.added_date %}
      <tr><th>added to catalog</th><td>{{ item.added_date|date }}</td></tr>
      {% endif %}
      <tr><td class="spacer" colspan="2">&nbsp;</td></tr>
      <tr><th>notes</th><td>{{ item.notes|markdown|safe }}</td></tr>
      {% if item.discogs %}
      <tr><th>discogs ref</th><td><a href="http://www.discogs.com/release/{{ item.discogs }}" target="_blank">{{ item.discogs }}</a></td></tr>
      {% endif %}
      <tr><td class="spacer" colspan="2">&nbsp;</td></tr>
      <tr><th>rarity class</th><td><img src="{{ item.rarity.scale_icon.url }}" alt="{{ item.rarity.code }}" title="{{ item.rarity.description}}&#013;&#013;Rated: {{ item.rarity_date }}"/></td></tr>
    </table>
    <div id="item-label-icons">
        {% for label in item.music_labels.all %}
          <a href="{{ label.url }}" title="{{ label.name }}" target="_blank"><img src="{{ label.icon.url }}" alt="{{ label.name }}"/></a>
        {% endfor %}
    </div>
  </div>
  {% include 'catalog/footer.html' %}
{% endblock %}

catalog/templates/catalog/listing.html
{% extends 'catalog/base.html' %}
{% load static %}

{% block title %}nincatalog.com - {{ listing.title }}{% endblock %}

{% block content %}
  {% include "catalog/header.html" with group=group selected=listing.selected %}
  {% for category in listing.categories %}
  <div class="row">
    <div id="category-listing" class="col-xs-12">
      <h6>{{ category.name }}</h6>
      <table>
        <thead>
          <tr>
            {% if not category.halo %}<th class="artist"><a href="{{ "?sort=artist" }}">artist</a></th>{% endif %}
            <th class="title"><a href="{{ "?sort=title" }}">title</a></th>
            <th><a href="{{ "?sort=notes" }}">notes</a></th>
            <th class="format"><a href="{{ "?sort=format" }}">format</a></th>
            <th class="catalog-number"><a href="{{ "?sort=catalog" }}">cat number</a></th>
            <th class="year"><a href="{{ "?sort=year" }}">yr</a></th>
            <th class="icon"><a href="{{ "?sort=country" }}">ctr</a></th>
            <th class="icon"><a href="{{ "?sort=rarity" }}">sc</a></th>
          </tr>
        </thead>
        <tbody>
        {% for item in category.items %}
        {% url 'item' category.tag item.tag as item_url %}
          <tr>
            {% if not category.halo %}<td class="artist"><a href="{{ item_url }}">{{ item.artist.name|lower }}</a></td>{% endif %}
            <td class="title"><a href="{{ item_url }}">{{ item.name|lower }}</a></td>
            <td><a href="{{ item_url }}">{{ item.description }}</a></td>
            <td class="format"><a href="{{ item_url }}">{{ item.media_format.name }}</a></td>
            <td class="catalog-number"><a href="{{ item_url }}">{{ item.catalog_number }}</a></td>
            <td class="year"><a href="{{ item_url }}">{{ item.year }}</a></td>
            <td class="icon"><a href="{{ item_url }}"><img src="{{ item.country.icon.url }}" alt="{{ item.country.name }}"/></a></td>
            <td class="icon"><a href="{{ item_url }}"><img src="{{ item.rarity.icon.url }}" alt="{{ item.rarity.code }}" /></a></td>
          </tr>
        {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
  {% endfor %}
  {% include 'catalog/footer.html' %}
{% endblock %}

catalog/templates/catalog/report.html
{% extends 'catalog/base.html' %}

{% block title %}nincatalog.com - {{ report.name|lower }}{% endblock %}

{% block content %}
    {% include "catalog/header.html" with group=group selected=report %}
    <div id="report">
      <table>
      {% for row in entries %}
        <tr>
        {% for entry in row %}
          <td class="icon">{% if entry.icon %}<img src="{{ entry.icon.url }}" alt="{{ entry.name }}"/>{% else %}&nbsp;{% endif %}</td>
          <td width="{{ report.column_width }}"><a href="{% url 'report_details' report.tag entry.pk %}">{{ entry.name }}</a></td>
          <td class="count">{{ entry.n_items }}</td>
          {% if not forloop.last %}<td class="spacer">&nbsp;</td>{% endif %}
        {% endfor %}
        </tr>
      {% endfor %}
      </table>
    </div>
    {% include 'catalog/footer.html' %}
{% endblock %}